# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(choices=[('p', 'Doctorate'), ('m', "Master's or professional degree"), ('b', "Bachelor's degree"), ('a', 'Associate degree'), ('hs', 'High school'), ('other', 'Other education')], max_length=30)),
                ('graduation_date', models.DateField()),
                ('subject', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=50)),
                ('school_city', models.CharField(max_length=30)),
                ('school_country', models.CharField(max_length=30)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='profiles.Profile')),
            ],
        ),
    ]