# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('cms', '0002_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='programpage',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Program'),
            preserve_default=False,
        ),
    ]
