# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_programpage_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programpage',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Program'),
        ),
    ]
