# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 15:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0028_merge'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('cms', '0007_frequentlyaskedquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='programpage',
            name='program',
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestion',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='FAQs', to='courses.Program'),
        ),
        migrations.DeleteModel(
            name='ProgramPage',
        ),
    ]
