# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financialaid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tierprogram',
            old_name='value',
            new_name='discount_amount',
        ),
        migrations.AddField(
            model_name='tierprogram',
            name='income_threshold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tierprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='courses.Program'),
        ),
    ]
