# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financialaid', '0002_auto_20160914_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaid',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='financialaid',
            name='program',
        ),
        migrations.AlterField(
            model_name='financialaid',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financialaid.TierProgram'),
        ),
    ]
