# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('courses', '0010_program_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['sort_order']},
        ),
        migrations.RemoveField(
            model_name='program',
            name='id',
        ),
        migrations.RemoveField(
            model_name='program',
            name='live',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=page_id, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='program',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='Courses', to='courses.Program'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='course',
            name='position_in_program',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
