# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20160503_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
