# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 16:39
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20160503_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
